language: ruby
sudo: false
notifications:
  slack:
    on_success: always
    on_failure: always
    on_start: never
    rooms:
      secure: tEC0voqIsLZ7saaJlbS1vinS6CeoPivHsMcqmAcibM3bwhPWD4ueQdEqKf93BG3R0DeFDU7NoCb2nN8Oyrtq89N9zVEpD4tzAQChQymUUfxF3/WTXzX6Ifubm8fi7HgJHROWC04aFSTf1HUFyh1GWxgtQ8j6DsV+E5vEn3pqHRmaNRl0UXJta49qU2OXJVdBzIYOhMhZMJaVZPGhbBIfKzhTjz6h8nxg/qbpm3TNbHXZmjBtMJs7Ru84u2/BEAdz7/we4PExi2woSPWHmdHWEuvvSk1ZMEP47unI1UvZ69bjBsAV7H8OhbTygfILnjkiJbawVGAgZ1+n2ztc6SI5PbgB50hKCgW6qwH+7fkDsXetEwEe6NACOozuG2SbRUHNhKcDdpy4JrdA17Z2FikmET1hzcve5ZCw+bV1sCISpXTYNkWLqQGkm/5VdFlvdgB2uPXq9h9gnY1gRjI5MLZ1GzF0WwTDqKPBKhhZFho7oyBZS6pdOOp0+yN/Pu3qKUl97sWBw/usJTpO6jNWQPqV5ItQOjlUc6/5T9TJjtXdaI+H0kNbHQTlyaha1uywt/3JG8OZLx1e4wLPz+CFpR0eWghRlQcZBU9YsyFUrPN8hxKcUTGHCBseSNXTkl9m08toQJKRmIJ0QOXjLR5MFIkMoO+O7eyuE7FKYcl0tt/YFbQ=
deploy:
  provider: rubygems
  api_key:
    secure: wbzyq51bpmG7i86AdZxSFGGMqvLvuCBnEIfhQx7cP3ZHH/f2kBqYI9MdcMiElK/J26yAjisYm/cZJP5AJWywEv1xabPKkMQuoCo339wLEeFRXVcR+A5rEC2lUMFw8tuC7zcTVhL06aYuNX2Dwt4dmIQ/jLT/C2+rOojV/4bVmN7P/zyaxxy+S+p68o/9o4CsvqQs2S3RU6kYgAwGwm+tfQb1F2hle3fXvLnbXKguv1p/B0XasRJH4nrPGLy9WSzAg2r+LawZw9XFgDlooyj4cdYNMw9FVGserxaBUPMLJnR1gv6BWgJCcbb6URQFMO6nqF0DFSa/Z/q3f0mtz5v1vmq266+kuEgxnfBdfP8/7tGxI+3ojTrpmqbwPw06PW4W4sFsmW91nP1Ve0EMKJh72bHgPi9SRbqR2sd9XJx3HBBPMl+xkoWs44zElvVjg3gRb8DAQXPf+2WW3nNZnBCUtfwqf576AyNqmt1oJXhEFySo8Lh1OnXPLkvR2kleDvHA6oEA5FzM8Sum0OFdOOZS8b+hsgV5IKDOWDaRj82xM5s1WyGbFPGJn8p21Mk12ksW+BfR08kGut+cEkZhNjHCCSde9AnQucVEyVLGxV1vr376JPT3yZyYuhGSrlL62onsMeqhzK0dkOZg6FtpE8FnQHDVRgZ2PjZVM3i1E+q83Ws=
  gemspec: gettyimages-api.gemspec
  on:
    tags: true
    repo: gettyimages/gettyimages-api_ruby
    branch: master
