language: ruby
sudo: false
script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ -n "$TRAVIS_TAG" ]; then PACKAGE_VERSION=$TRAVIS_TAG;
  fi
- printenv | grep TRAVIS | sort
- echo $PACKAGE_VERSION
- sed -i -e "s/0.0.0/$PACKAGE_VERSION/" ./lib/GettyImagesApi/version.rb
- git add ./lib/GettyImagesApi/version.rb && git commit -m 'update version'
deploy:
  provider: rubygems
  gem: gettyimages-api
  gemspec: gettyimages-api.gemspec
  on:
    tags: true
    repo: gettyimages/gettyimages-api_ruby
    branch: master
  api_key:
    secure: bhHKmTwLFQc9Alw4qCXgKOsjKsp0LEzg9/VyHHmY5+DW6BGy0+HKDj7BbYr8rHcBsDiXzL5hj6Jzbohg25jznu8u/KgqycRZtP5DNStAR/bPznov0SavcvQOCpaUFua5ilEwuLGdDnekOJtxhZ0eM3oxUfk2REASirBeUYXAoyqoSqeGCg42aPFQU9hAG7TC/E0R/bQgwKXnOTQU/ybsnva2fobp4a813Q4SnPz8NQ0axYKmFA8YVawZxO35ikMEgMZ+yWJRtky+C4TiSc/4kM1XuFN0e34ryzFz9bxNBw51vFmXyTYnU9gsEXs8bufkxrvtdjEoVUQn9t5kgjurzy6mMTGBSBchcCfty3AUQEW0YjGolnSsS+uOl5Nig/ibTodJh6C6J5hYKnQ9rjU/1gG7V9yowuGJXjGHgJZlj/68v01nc5xHUVcfWpMUzvqyuvEwoZ3YB3orx4HHA0aNDTkp2gU7rrpJKNOxEMDmCmfbLgtXaqEq0/asJUYZgf0nvqUM+Xxq2ZeFU0d9vSDDi1G6o3SpXzXay00IZQ1SagyMZZevWiMnjMu+tIJz1cJY+CiZMtI0VM7fCC7lOBvRQn8XQdUHk1rCru0DtMDKyytKReFnmRZiAkPEuqFGQCg9dfrmOSo/+f1LQE+GOJSzDdh4b2lqjWfEIqQED+e5tjo=
